### ISSUE TITLE
Hexx Rewritten 3 and 4 vanished

### ISSUE THREAD

**Issue by Yosefpoysun** [AMPZNetwork/Hexx-Rewritten#3]
Likely something you are aware of seeing as it happened after a recent update, but the two modpacks referenced in the title can't be run through Technic and are now vanished from the launcher.  As I said, you probably already know but either way, there it is.

Thanks

**Comment by LabsZero** [comment]
Thank you for your ticket, this issue has been resolved. 

Note a launcher restart my be needed to ensure that the launcher is using the up to date URL.
