### ISSUE TITLE
Hexx Rewritten 3 disappears when opening world in singleplayer mode

### ISSUE THREAD

**Issue by iMichael02** [AMPZNetwork/Hexx-Rewritten#4]
As the title says, I can't play in singleplayer mode. When I open a world, the game just disappears and Technic launcher shows up. I can still join my friends' servers and play normally. I don't know what's the problem here. Can anyone help, please?

**Comment by LabsZero** [comment]
Could you please attach a crash log or log located in your default technic launcher install folder.

**Comment by iMichael02** [comment]
I reinstalled my windows and it's all normal now

Vào CN, 25 thg 10, 2020 vào lúc 04:19 LabsZero <notifications@github.com>
đã viết:
